version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: notesync-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesync
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notesync-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notesync-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/notesync
      - PORT=5000
      - JWT_SECRET=seu_jwt_secret_aqui
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - notesync-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notesync-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - notesync-network

volumes:
  postgres_data:
    driver: local

networks:
  notesync-network:
    driver: bridge
